# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Run Test for AISimulator
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/frontend/ai_simulator/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Run Test for SuperScaler Executor
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/backend/common/executor/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Run Test for Plan Generator
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/frontend/plan_gen/Dockerfile'
        tags: |
          $(tag)