# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

pool:
  name : NNFusion CI
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndRun
  jobs:
  - job: BuildAndRun
    steps:
    - script: docker build -t superscaler_cuda -f Dockerfile.test.CUDA . 
    - script: docker run --runtime=nvidia --rm superscaler_cuda
