# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name : NNFusion CI
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:  
  - job: BuildDocker
    steps:
    - script: docker build -t superscaler_cuda -f Dockerfile.test.CUDA . 
- stage: Run
  jobs:
  - job: RunUniTest
    steps:
    - script: docker run --runtime=nvidia --rm superscaler_cuda
